kind = "DojoContract"
class_hash = "0x4e02bf9aa55d5347912fadecd7e9847e41af04e334f0e689adebf8c6b28f10a"
original_class_hash = "0x4e02bf9aa55d5347912fadecd7e9847e41af04e334f0e689adebf8c6b28f10a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"
