kind = "DojoContract"
class_hash = "0x4bb3c568f7832411d975a55be86eccb0fe15ce8a9f9ef42029320125fe8bf6a"
original_class_hash = "0x4bb3c568f7832411d975a55be86eccb0fe15ce8a9f9ef42029320125fe8bf6a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"
