kind = "DojoContract"
class_hash = "0x72e53d4a52a00708f5c75da68a726b969a3d5aa016afbca357cdbbbdcc4a8d"
original_class_hash = "0x72e53d4a52a00708f5c75da68a726b969a3d5aa016afbca357cdbbbdcc4a8d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"
