kind = "DojoContract"
class_hash = "0x3aa48bac5810438a266ea978e7317c3082f6b6a6563bdf3cf49857977bb9dee"
original_class_hash = "0x3aa48bac5810438a266ea978e7317c3082f6b6a6563bdf3cf49857977bb9dee"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = []
init_calldata = []
tag = "pistols64-actions"
systems = [
    "create_challenge",
    "reply_challenge",
    "commit",
    "reveal",
]
manifest_name = "pistols64-actions-67633088"
